version: '3.8'

services:
  auditor:
    build: Auditor/
    container_name: auditor
    network_mode: host
    ports:
      - 12345

  jogador:
    build: Jogador/
    container_name: jogador
    network_mode: host
    ports:
      - "12345:12345"
    depends_on:
      - auditor 